### PR TITLE
Long word sources, de.

### PR DESCRIPTION
**Pull request by poetaster**
Added the source files for collaborative editing and Makefile as per example (fr).

### CODE REVIEW

**Comment by poetaster** [comment]
Err. Forgot to squash first, and don't think I completed it correctly on pass two.  I should be able to do ~HEAD 5 and squash  just the last five?

**Comment by monich** [comment]
> Err. Forgot to squash first, and don't think I completed it correctly on pass two. I should be able to do ~HEAD 5 and squash just the last five?

The diff looks fairly clean, "squash and merge" would probably do the right thing but I'd prefer if you do the squashing.

**Comment by poetaster** [comment]
okidoke.

**Comment by monich** [comment]
BTW you didn't have to close this PR, you could `push -f` the same remote branch, GitHub would handle that just fine, i.e. the branch would remain associated with the same PR, I do that all the time. And it's generally a good idea to submit PRs from a working branch rather than master.

**Comment by poetaster** [comment]
Yeah, I was just unhappy with the reflog :) I admit i hate rebasing (I'm a darcs user, who still dislikes git). I'll branch for future work. Though I do love living dangerously (kidding, bit me with Tidings recently).

**Comment by poetaster** [comment]
Just to clarify for my Readme. I'm going to branch, at least, 'Working' (perhaps working-words, working-xwords) and then do PRs to your master. Like feature branching? That should keep the logs clean (obviously, I kept pulling in master mixed with x commits of my own.)

**Comment by monich** [comment]
Typical workflow is to keep your master in sync with the upstream (source of the fork), do all your work on a branch (branches), submit PRs from the branches, fast-forward your master once they get merged (i.e. re-sync your master with the upstream) and then rebase other working branches, if you have any.

**Comment by poetaster** [comment]
Yo, that sounds excatly like what I had in mind. Okidoke! Thanks!

**Pull request closed without merging**
