### PR TITLE
German language dicts.

### PR DESCRIPTION
**Pull request by poetaster**
Tool works :) This initial set is playable, but, in short, I'm probably going to get some hate from the Germans. Next week I'll build a less bitchy set. But, this is a good start!

Thanks!

### CODE REVIEW

**Comment by monich** [comment]
Could you squash those commits into one?

**Comment by monich** [comment]
Two z's was one too many))

**Comment by poetaster** [comment]
> Could you squash those commits into one?

Hmmm, can't you do squash on merge? I'm not sure how to squash on pull?

**Comment by poetaster** [comment]
Well, I'm so tired, it's not surprise an extra Z got int there ;)

**Comment by monich** [comment]
> > Could you squash those commits into one?
> 
> Hmmm, can't you do squash on merge? I'm not sure how to squash on pull?

Yeah, I can do a squash merge.

**Comment by poetaster** [comment]
> > > Could you squash those commits into one?
> > 
> > 
> > Hmmm, can't you do squash on merge? I'm not sure how to squash on pull?
> 
> Yeah, I can do a squash merge.

Thanks. Sleep! ZZZ.

**Pull request merged**
