### PR TITLE
[pt_BR] add translation

### PR DESCRIPTION
**Pull request by caio2k**
[translations] Added Brazilian Portuguese translation

### CODE REVIEW

**Comment by monich** [comment]
Thanks!

**Comment by monich** [comment]
I guess it's ok if I change pt_BR => pt to cover all Portuguese locales, not just Brazil.

**Comment by caio2k** [comment]
hello @monich , first thanks for this game and all the other useful apps you developed!
I'm fine with converting `pt_BR` into `pt`, but if you want I can also create the `pt` locale in addition of `pt_BR`. Although they have similar words, some are more used in Brazil than in Portugal, and vice-versa.

**Comment by monich** [comment]
Yes, if there's a significant enough difference please add pt_PT translation too!

**Pull request merged**
