### PR TITLE
DE dict files.

### PR DESCRIPTION
**Pull request by poetaster**
Added one line / word dict files, de.
Added a make file for de dict directory.

### CODE REVIEW

**Comment by monich** [comment]
Thanks!

**Comment by monich** [comment]
And I just cleaned them up a bit, you better pull that in and rebase your changes (if you have any) on top of it

**Comment by poetaster** [comment]
Hmmm. I'm not sure why (well, the encoding?) xwords was probably a waste of time. Some of the deletions (why remove böcke? from words.txt?) I'm unclear on. I'm not entirely certain that I want to rebase on those changes, but I'll pull them and compare. maybe you've done me a favour :)

**Comment by monich** [comment]
böcke must have been removed by mistake, I'll add it back!

**Comment by monich** [comment]
Yeah, when I was removing the duplicates I (accidentally) removed böcke from words.txt and left one in xwords.txt
I moved it back to the main dictionary.

**Comment by poetaster** [comment]
Ah, damn it. I just shouldn't have pushed you those files. We're doing the same stuff in parallel. Ok, xwords.txt should, actually, only contain words we don't permit but which 'could' come to mind for the german reader/speaker, correct? I was trying to be more intelligent with that than I had been (xwords had just been a diff the words from an online wordle source and a german dictionaries 5 letter words). The process I had started on was to merge the legit words from xwords into words.

**Comment by monich** [comment]
- `words` is the list from which the word to be guessed is randomly picked. All these words can also be used for checking.

- `xwords` is the list of additional words which can be used only for checking (I was thinking slang, alternative spellings, politically incorrect words and such - anything that isn't considered proper language)

It obviously doesn't make sense to have the same word in both lists, let alone repeating it several times. And actually, wordle-tool removes the duplicates. But from the maintenance PoV better to not have duplicates in the source files too, to avoid confusion and duplicate work.

BTW if you run `make V=-v` wordle-tool will complain about duplicates.

**Comment by poetaster** [comment]
Ok, that's all as I thought it should be. I just pushed too soon since I was in mid-process. I have a habit to doing a lot of granual commits which doesn't fit with tis case.

make V=-v , very good. thanks.

**Comment by monich** [comment]
Normally PRs are submitted when a piece of work is ready for merge, that's what I assume. If you submit a PR and then realize that it's not ready yet, please mark it as draft so that it doesn't accidentally get merged too soon.

**Pull request merged**
