### PR TITLE
Portuguese dict

### PR DESCRIPTION
**Pull request by caio2k**
add support for pt_BR dict.
Note that I had to remove a `toLower` in order to load properly the Brazilian Portuguese dict. Probably it is related with not working previously with any language with a dash+something like `_BR` from `pt_BR`, where the last part is in upper case.

### CODE REVIEW

**Comment by monich** [comment]
Is that really Brasileiro specific or would it be acceptable for any Portuguese speaker?

**Comment by caio2k** [comment]
Hello @monich, that's a good idea. The dict still needs lots of improvement, and I can focus on keeping only the words that have the same spelling in both Brazil and Portugal (which should be >95% of the words). There are other countries speaking Portuguese as well, but those should be ok to use BR+PT dict.

**Comment by monich** [comment]
Ok, let's take this as is and then I'll probably turn pt_BR into just pt

**Comment by monich** [comment]
Actually it already was pt 🙂 Thanks!

**Pull request merged**
